[package]
authors = ["keringar <wanrunhu@gmail.com>"]
name = "coin"
version = "0.1.0"

[dependencies]
error-chain = "0.11.0"
hyper = "0.11.6"
ring = "0.12.1"
serde = "1.0.20"
serde_derive = "1.0.20"
serde_json = "1.0.6"
websocket = "0.20.2"
